In [11]:
#Import libraries
import numpy as np
import pandas as pd

In [12]:
arr = np.array([10,20,30,40,50,60,70])
print(arr)
print("\nAverage number", arr.mean())

[10 20 30 40 50 60 70]

Average number 40.0


In [13]:
#working with the index
print(arr[3])
print(arr[2])
print(arr[-2])
print(arr[6])
print(arr[-4])
print(arr[-1])


40
30
60
70
40
70


In [14]:
#slicing
print(arr[1:6])
print(arr[6:])
print(arr[:7])
print(arr[-6:-1])
print(arr[7:])
print(arr[-1:-6])

[20 30 40 50 60]
[70]
[10 20 30 40 50 60 70]
[20 30 40 50 60]
[]
[]


In [17]:
#working with 2D array
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    
])

print(matrix[0, 1])
print(matrix[1, :])
print(matrix[1:2, 2])
print(matrix[2, :2])
print(matrix[1:2, 0:2])

2
[4 5 6]
[6]
[7 8]
[[4 5]]


In [18]:
#changing 1D to 2D array
arr2 = np.arange(1,13)
reshape = arr2.reshape(3,4)

print("Original Array: ", arr2)
print("\nReshape array ", reshape)

Original Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshape array  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
#changing 2D to 1D array
flatten = reshape.flatten()
print("Flatten: ", flatten)

Flatten [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
#working with basic maths operations
arr3 = np.array([1,2,3,4,5])
arr4 = np.array([10,20,30,40,50])


#bsic operators
print(arr3 + arr4)
print(arr3 - arr4)
print(arr3 * arr4)
print(arr3 / arr4)


#Scaler operator
print(arr4 ** 2)
print(arr4 // 2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[ 100  400  900 1600 2500]
[ 5 10 15 20 25]


In [25]:
#Using dot product
matrix1 = np.array([
    [1,2],
    [3,4]
])

matrix2 = np.array([
    [5,6],
    [7,8]
])

dot = np.dot(matrix1,matrix2)
print("Dot Product\n:", dot)

#multiply
multiply = matrix1 * matrix2 
print("Multiply\n", multiply)

Dot Product
: [[19 22]
 [43 50]]
Multiply
 [[ 5 12]
 [21 32]]
